import { lazy } from "react";

export * from "./AllComponents/BadgeClasse";
export * from "./AllComponents/BlockSemester";
export * from "./AllComponents/DataClasses";
export * from "./AllComponents/DataPensum";
export * from "./AllComponents/DataProfession";
export * from "./AllComponents/DataScores";
export * from "./AllComponents/DataStudents";
export * from "./AllComponents/DataTeacher";
export * from "./AllComponents/InputForm";
export * from "./AllComponents/PersonsForms";
export * from "./AllComponents/Popup";
export * from "./AllComponents/Select";
export * from "./AllComponents/Sidebar";
export * from "./AllComponents/TableComponent";
export * from "./AllComponents/TablePersons";
export * from "./AllComponents/Profile";
export * from "./AllComponents/Teacher";
export * from "./AllComponents/ProfessionSemester";
export * from "./AllComponents/Record";
export * from "./AllComponents/SectionClasses";

// export const BadgeClasse = lazy(() => import('./AllComponents/BadgeClasse'));
// export const BlockSemester = lazy(() => import('./AllComponents/BlockSemester'));
// export const DataClasses = lazy(() => import('./AllComponents/DataClasses'));
// export const DataPensum = lazy(() => import('./AllComponents/DataPensum'));
// export const DataProfession = lazy(() => import('./AllComponents/DataProfession'));
// export const DataScores = lazy(() => import('./AllComponents/DataScores'));
// export const DataStudents = lazy(() => import('./AllComponents/DataStudents'));
// export const DataTeacher = lazy(() => import('./AllComponents/DataTeacher'));
// export const InputForm = lazy(() => import('./AllComponents/InputForm'));
// export const PersonsForms = lazy(() => import('./AllComponents/PersonsForms'));
// export const Popup = lazy(() => import('./AllComponents/Popup'));
// export const Select = lazy(() => import('./AllComponents/Select'));
// export const Sidebar = lazy(() => import('./AllComponents/Sidebar'));
// export const TableComponent = lazy(() => import('./AllComponents/TableComponent'));
// export const TablePersons = lazy(() => import('./AllComponents/TablePersons'));
// export const Profile = lazy(() => import('./AllComponents/Profile'));
// export const Teacher = lazy(() => import('./AllComponents/Teacher'));
// export const ProfessionSemester = lazy(() => import('./AllComponents/ProfessionSemester'));
// export const Record = lazy(() => import('./AllComponents/Record'));
// export const SectionClasses = lazy(() => import('./AllComponents/SectionClasses'));