export * from "./AllComponents/InputForm";
export * from "./AllComponents/PersonsForms";
export * from "./AllComponents/TableComponent";
export * from "./AllComponents/TablePersons";
export * from "./AllComponents/BadgeClasse";
export * from "./AllComponents/BlockSemester";
export * from "./AllComponents/DeletePopUp";
export * from "./AllComponents/Popup";
export * from "./AllComponents/ProfessionSemester";
export * from "./AllComponents/Record";
export * from "./AllComponents/Select";
export * from "./AllComponents/SectionClasses";
export * from "./AllComponents/Select";
export * from "./AllComponents/Sidebar";
export * from "./AllComponents/Teacher";
export * from "./AllComponents/Loading";

export * from "./AllComponents/Input";
export * from "./AllComponents/Button";